### PR TITLE
text-sidebar-title-cy-405

### PR DESCRIPTION
**Pull request by steiningermona**

### CODE REVIEW

**Comment by diegomart2000** [comment]
@steiningermona Icon size gets affected by text length and also the text is not vertically centered. You could change the container text to be flex and items centered.

Screen Shot 2021-11-17 at 9 54 26 AM
Screen Shot 2021-11-17 at 9 56 29 AM

**Review by diegomart2000 — CHANGES_REQUESTED** [review]
Please check "conversation" for comments.

**Review by diegomart2000 — CHANGES_REQUESTED** [review]
@steiningermona Text is still not centered relative to the toggle. Toggle has a height of 20px and the text is 16px. It has to be centered.

**Comment by steiningermona** [comment]
> @steiningermona Text is still not centered relative to the toggle. Toggle has a height of 20px and the text is 16px. It has to be centered.

I think I finally managed it, I was already becoming mad at my chrome inspect tools. :D

**Review by diegomart2000 — APPROVED** [review]

**Pull request merged**
