### PR TITLE
images-previews-cy-101-fixes

### PR DESCRIPTION
**Pull request by cris22380**

### CODE REVIEW

**Comment by diegomart2000** [comment]
https://github.com/caisy-io/league/blob/dev/CONTRIBUTION.md

**Comment by cris22380** [comment]
- preview-text-default size: 12
Screen Shot 2021-12-07 at 10 34 34

- preview-text-default size: 16
Screen Shot 2021-12-07 at 10 35 02

- preview-text-default size: 20
Screen Shot 2021-12-07 at 10 36 32

Screen Shot 2021-12-07 at 10 36 49
Screen Shot 2021-12-07 at 10 37 11
Screen Shot 2021-12-07 at 11 18 58
Screen Shot 2021-12-07 at 11 19 16
Screen Shot 2021-12-07 at 11 19 47
Screen Shot 2021-12-07 at 11 26 28

**Comment by cris22380** [comment]
- preview-text-default size:16
Screen Shot 2021-12-07 at 11 34 52

- preview-text-default size: 20
Screen Shot 2021-12-07 at 11 35 11

- preview-text-default size: 24
Screen Shot 2021-12-07 at 11 35 36

- preview-text-default size: 28
Screen Shot 2021-12-07 at 11 35 56

- preview-text-default size: 32
Screen Shot 2021-12-07 at 11 36 10

- preview-text-default size: 36
Screen Shot 2021-12-07 at 11 36 26

- preview-text-default size: 40
Screen Shot 2021-12-07 at 11 36 39

- preview-text-default size: 48
Screen Shot 2021-12-07 at 11 36 50

- figma
Screen Shot 2021-12-07 at 11 37 09

**Comment by cris22380** [comment]
- preview-icon-default size:16
Screen Shot 2021-12-07 at 11 48 00

- preview-icon-default size: 20
Screen Shot 2021-12-07 at 11 48 25

- preview-icon-default size:24
Screen Shot 2021-12-07 at 11 48 47

- preview-icon-default size:28
Screen Shot 2021-12-07 at 11 49 00

- preview-icon-default size:32
Screen Shot 2021-12-07 at 11 49 10

- preview-icon-default size:36
Screen Shot 2021-12-07 at 11 49 27

- preview-icon-default size:40
Screen Shot 2021-12-07 at 11 49 41

- preview-icon-default size:48
Screen Shot 2021-12-07 at 11 49 53

- figma
Screen Shot 2021-12-07 at 11 50 30

**Comment by cris22380** [comment]
- preview-image-default size: 16
Screen Shot 2021-12-07 at 12 23 03

- preview-image-default size: 20
Screen Shot 2021-12-07 at 12 23 15

- preview-image-default size: 24
Screen Shot 2021-12-07 at 12 23 24

- preview-image-default size: 28
Screen Shot 2021-12-07 at 12 23 33

- preview-image-default size: 32
Screen Shot 2021-12-07 at 12 23 48

- preview-image-default size: 36
Screen Shot 2021-12-07 at 12 23 56

- preview-image-default size: 40
Screen Shot 2021-12-07 at 12 24 05

- preview-image-default size: 48
Screen Shot 2021-12-07 at 12 24 13

- figma
Screen Shot 2021-12-07 at 12 24 27

**Review by diegomart2000 — APPROVED** [review]

**Comment by cris22380** [comment]
- preview-flag-default  size: 12
Screen Shot 2021-12-07 at 12 29 16

- preview-flag-default  size: 16
Screen Shot 2021-12-07 at 12 27 01

- preview-flag-default  size: 20
Screen Shot 2021-12-07 at 12 27 19

- preview-flag-default  size: 24
Screen Shot 2021-12-07 at 12 27 27

- preview-flag-default  size: 28
Screen Shot 2021-12-07 at 12 27 35

- preview-flag-default  size: 32
Screen Shot 2021-12-07 at 12 27 45

- preview-flag-default  size: 36
Screen Shot 2021-12-07 at 12 27 58

- preview-flag-default  size: 40
Screen Shot 2021-12-07 at 12 28 08

- preview-flag-default  size: 48
Screen Shot 2021-12-07 at 12 28 17

- figma
Screen Shot 2021-12-07 at 12 29 43

**Pull request merged**
