### PR TITLE
button-fix-visual-defects-cy-636

### PR DESCRIPTION
**Pull request by cris22380**

### CODE REVIEW

**Comment by cris22380** [comment]
- From storybook
Screen Shot 2022-01-05 at 17 50 32

- From  figma
Screen Shot 2022-01-05 at 17 51 58

- From storybook
Screen Shot 2022-01-05 at 17 51 46

- From  figma
Screen Shot 2022-01-05 at 17 50 51

**Review by diegomart2000 — CHANGES_REQUESTED** [review]
@cris22380 there is a second shadow being applied to the second button.

Screen Shot 2022-01-05 at 7 05 03 PM

Look at the button on right side, the shadow is darker.

**Comment by cris22380** [comment]
- From storybook
Screen Shot 2022-01-06 at 08 52 54

**Comment by cris22380** [comment]
Size default

- From storybook
Screen Shot 2022-01-06 at 10 41 08

- From storybook
Screen Shot 2022-01-06 at 10 41 12

- From storybook
Screen Shot 2022-01-06 at 10 41 21

- From storybook
Screen Shot 2022-01-06 at 10 41 28

- From figma
Screen Shot 2022-01-06 at 10 41 43

Size medium
- From storybook
Screen Shot 2022-01-06 at 10 44 07

- From storybook
Screen Shot 2022-01-06 at 10 44 13

- From storybook
Screen Shot 2022-01-06 at 10 44 30

- From storybook
Screen Shot 2022-01-06 at 10 44 36

- From figma
Screen Shot 2022-01-06 at 10 44 49

Size small
- From storybook
Screen Shot 2022-01-06 at 10 46 27

- From storybook
Screen Shot 2022-01-06 at 10 46 30

- From storybook
Screen Shot 2022-01-06 at 10 46 33

- From storybook
Screen Shot 2022-01-06 at 10 46 40

- From figma
Screen Shot 2022-01-06 at 10 46 55

Size Micro
- From storybook
Screen Shot 2022-01-06 at 10 48 40

- From storybook
Screen Shot 2022-01-06 at 10 48 45

- From storybook
Screen Shot 2022-01-06 at 10 48 51

- From storybook
Screen Shot 2022-01-06 at 10 48 57

**Review by diegomart2000 — APPROVED** [review]

**Pull request merged**
