### PR TITLE
Cy 84 layouts

### PR DESCRIPTION
**Pull request by radicaa**

### CODE REVIEW

**Comment by MoritzGruber** [comment]
@radicaa  please resolve the conflicts with dev 🙈

**Comment by diegomart2000** [comment]
@MoritzGruber @radicaa is this PR actually valid? 212 files updated doesn't seem correct, maybe it was cut of master or something.

**Comment by radicaa** [comment]
Merged current dev into this branch and resolved merge conflicts. Should be mergeable now

**Comment by radicaa** [comment]
SidebarTag still needs to be refactored (removed from Button component into own component)

**Comment by radicaa** [comment]
Fixed the sidebarTag. Can be reviewed now. 

What is new (because it seems a lot):
- Layout (old layout is still in the project and is called legacyLayout now),
- resizable component,
- movable component, 
- stackable component, 
- sidebarTag component

**Review by MoritzGruber — APPROVED** [review]

**Pull request merged**
