### PR TITLE
implement-navigational-icons-cy-555

### PR DESCRIPTION
**Pull request by cris22380**

### CODE REVIEW

**Comment by cris22380** [comment]
- cross from storybook size: 16
cross 16

- cross from storybook size: 20
cross 20

- cross from storybook size: 24
cross 24

- cross from storybook size: 32
cross 32

- cross from figma
cross figma

**Comment by cris22380** [comment]
- chevron down from storybook size: 16
down 16

- chevron down from storybook size: 20
down 20

- chevron down from storybook size: 24
down 24

- chevron down from storybook size: 32
down 32

- chevron down from figma
down figma

**Comment by cris22380** [comment]
- chevron left from storybook size: 16
left 16

- chevron left from storybook size: 20
left 20

- chevron left from storybook size: 24
left 24

- chevron left from storybook size: 32
left 32

- chevron left from figma
left figma

**Comment by cris22380** [comment]
- chevron right from storybook size: 16
right 16

- chevron right from storybook size: 20
right 20

- chevron right from storybook size: 24
right 24

- chevron right from storybook size: 32
right 32

- chevron right from figma
right figma

**Comment by cris22380** [comment]
- chevron up from storybook size: 16
up 16

- chevron up from storybook size: 20
up 20

- chevron up from storybook size: 24
up 24

- chevron up from storybook size: 32
up 32

- chevron up from figma
up figma

**Comment by cris22380** [comment]
- chevron dragable from storybook size: 12
dragable 12

- chevron dragable from storybook size: 16
dragable 16

- chevron dragable from storybook size: 20
dragable 20

- chevron dragable from storybook size: 24
dragable 24

- chevron dragable from storybook size: 32
dragable 32

- chevron dragable from figma
dragable figma

**Review by diegomart2000 — APPROVED** [review]

**Pull request merged**
